# Generated by Django 4.2 on 2023-04-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_remove_student_emp_id_remove_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
