# Generated by Django 4.2 on 2023-04-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_rename_name_subject_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='name',
        ),
    ]
