# Generated by Django 4.2 on 2023-04-07 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_remove_subject_student_subjectmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmark',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.student'),
        ),
    ]
